# Generated by Django 5.0.6 on 2024-08-26 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='use_name',
            new_name='user_name',
        ),
    ]
